version: "3"
services:
  app:
    restart: always
    build: .
    command: >
      bash -c
      "gunicorn -w4 -b 0.0.0.0:8000 --log-level=debug --access-logfile error.log manage:app"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - mysql
    networks:
      - web_network
      - db_network
  mysql:
    image: mysql:5.7
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=2018010717
      - MYSQL_DATABASE=thss
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - db_network
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./application/templates:/code/templates
      - ./application/static:/code/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
